JonTimExamen/JonTimExamen/Models/Visitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JonTimExamen.Models
{
    public class Visitor
    {
        public int Id { get; set; }
        [Required]
        public virtual string FirstName { get; set; }
        [Required]
        public virtual string LastName { get; set; }
        [Required]
        public virtual string Company { get; set; }
        public virtual DateTime CheckInTime { get; set; }
        public virtual DateTime CheckOutTime { get; set; }
        [Required]
        public virtual string RandomNumber { get; set; }
        public string ImageBase64String { get; set; }

    }
}

JonTimExamen/JonTimExamen/Controllers/VisitorController.cs
using JonTimExamen.Models;
using JonTimExamen.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace JonTimExamen.Controllers
{
    public class VisitorController : Controller
    {
        private WebDbContext db;
        private readonly IHostingEnvironment _environment;

        public VisitorController(WebDbContext db, IHostingEnvironment hostingEnvironment)
        {
            _environment = hostingEnvironment;
            this.db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CheckOut()
        {
            return View();
        }

        public string CalculateRandomNumber()
        {
            byte[] buffer = new byte[5];
            Random r = new Random();
            r.NextBytes(buffer);
            var randomNumber = BitConverter.ToString(buffer);

            return randomNumber;
        }

        [HttpPost]
        public IActionResult CheckIn(Visitor visitor)
        {

            db.Visitor.Add(visitor);
            visitor.CheckInTime = DateTime.Now;
            
            visitor.RandomNumber = CalculateRandomNumber();
            bool number = db.Visitor.Any(u => u.RandomNumber == visitor.RandomNumber);

            while(number == true)
            {
                visitor.RandomNumber = string.Empty;
                visitor.RandomNumber = CalculateRandomNumber();
            }

            ViewBag.visitor = visitor;

            db.SaveChanges();

            return View("Capture");
        }

        [HttpPost]
        public IActionResult Capture(Visitor visitor)
        {
            ViewBag.visitor = visitor;

            visitor = db.Visitor.OrderByDescending(d => d.CheckInTime).FirstOrDefault();

            var pictures = HttpContext.Request.Form.Files;

            if (pictures != null)
            {
                foreach (var picture in pictures)
                {
                    if (picture.Length > 0)
                    {
                        var pictureName = picture.FileName;
                        var uniquePictureName = visitor.RandomNumber;
                        var pictureExtension = Path.GetExtension(pictureName);

                        var finalPictureName = string.Concat(uniquePictureName, pictureExtension);
                        var filePath = Path.Combine(_environment.WebRootPath, "visitorPhotos") + $@"\{finalPictureName}";

                        if (!string.IsNullOrEmpty(filePath))
                        {
                            StoreInFolder(picture, filePath);
                        }

                        var imageBytes = System.IO.File.ReadAllBytes(filePath);

                        if (imageBytes != null)
                        {
                            string base64String = Convert.ToBase64String(imageBytes, 0, imageBytes.Length);
                            string imageUrl = string.Concat("data:image/jpg;base64,", base64String);
                            visitor.ImageBase64String = imageUrl;
                        }
                    }
                }
            }

            db.SaveChanges();
            return View("Capture");
        }

        public IActionResult QrView()
        {
            return View();
        }

        private void StoreInFolder(IFormFile picture, string pictureName)
        {
            using (FileStream fs = System.IO.File.Create(pictureName))
            {
                picture.CopyTo(fs);
                fs.Flush();
            }
        }

        [HttpPost]
        public IActionResult CheckOut(Visitor visitor)
        {
            string rnum = Request.Form["RandomNumberInput"];
            ViewData["rnum"] = rnum;
            // var visitorId = db.Visitor.OrderByDescending(v => v.RandomNumber).Select(v => v.RandomNumber).FirstOrDefault();
            var itemToEdit = db.Visitor.SingleOrDefault(x => x.RandomNumber == rnum);

            if (itemToEdit != null && itemToEdit.CheckInTime > itemToEdit.CheckOutTime)
            {
                itemToEdit.CheckOutTime = DateTime.Now;
            }

            else
            {
                ViewBag.error = "Wrong visitor ID";
                return View("Checkout");
            }


            db.SaveChanges();

            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("CurrentVisitors");
            }


            return View("Thx");
        }

        [Authorize]
        public IActionResult History(Visitor visitor)
        {
            List<Visitor> model = db.Visitor
                .ToList();

            return View(model);
        }


        [Authorize]
        public IActionResult CurrentVisitors(Visitor visitor)
        {
            List<Visitor> model = db.Visitor
            .ToList();

            return View(model);
        }

        public IActionResult Print()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

JonTimExamen/JonTimExamen/Views/Visitor/Capture.cshtml
@model Visitor
@{
    ViewData["Title"] = "Capture";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<section class="hero">
    <div class="row" id="pic" style="margin: auto">
        <div class="col-md-12">
            <form method="post" asp-controller="Visitor" asp-action="Capture">

                <div class="form-group">
                    <div class="center-block" id="camera">

                    </div>
                </div>

                <div class="form-group">
                    <div id="results">

                    </div>
                </div>

                <div id="pictureButton" class="form-group">
                    <button type="button" class="btn btn-default center-block" value="Take Picture" style="width:150px" onclick="takePicture(); removeAndShowButtons()">Take a Picture</button>
                </div>
            </form>
            <div id="finishButton" class="col-md-12" style="display:none">
                <input type="button" value="Finish" class="btn btn-success center-block" onclick="hideAndShow()" />
            </div>
        </div>
    </div>

    <div class="row" id="qr" style="display:none;">
        @if (ViewBag.visitor != null)
        {
            var name = ViewBag.visitor.FirstName;
            var lastName = ViewBag.visitor.LastName;
            var company = ViewBag.visitor.Company;
            var number = ViewBag.visitor.RandomNumber;

            <p><b>@name @lastName</b></p>
            <p><b>@company</b></p>
            <qrcode content="@number" width="200" height="200" />
            <p><b>@number</b></p>
        }
    </div>
    <div class="row" id="backBtn" style="display: none">
        <button type="button" class="btn btn-default" value="Back" onclick="textAndBack()">Back</button>
    </div>

    <div class="hero-inner" id="captureHeroText" style="margin: auto; display: none; text-align: center">
        <h1 id="captureHeroH1" style="display: none">Thank you</h1>
        <h1 id="captureHeroH2" style="display: none">Dont forget to checkout when leaving</h1>
    </div>

</section>

<script src="~/webcam/webcam.js"></script>
<script src="~/js/site.js"></script>

JonTimExamen/JonTimExamen/Views/Visitor/CheckOut.cshtml
@model Visitor
@{
    ViewData["Title"] = "CheckOut";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<section class="hero">
    <div class="row" id="formDiv" style="margin: auto; text-align: center">
        <h2>Enter your visitor ID to check out</h2>
        <br />
        <form method="post" asp-controller="Visitor" asp-action="CheckOut">

            <div><p style="color: red; font-size: 25px">@ViewBag.error</p></div>

            <div class="form-group">
                <input required="required" asp-for="@Model.RandomNumber" class="form-control" name="RandomNumberInput" id="RandomNumberInput" runat="server" />
            </div>

            <p id="infoLink" style="text-decoration: underline" onclick="showInfoText()">
            (Can't find your visitor id?)
            </p>

            <div id="Info" class="hidden" style="width: 400px">
                <p id="infoText">
                    You can find your visitor ID at the bottom of your visitor badge.
                    It should look something like this : A9-0D-82-4F-B9
                </p>
            </div>

            <div class="form-group">
                <label name="ErrorLabel"></label>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success center-block" value="Check out" style="width:150px">Check out</button>
            </div>
        </form>

    </div>

</section>

<script src="~/js/site.js"></script>

JonTimExamen/JonTimExamen/Views/Visitor/CurrentVisitors.cshtml
@model List<Visitor>
@{
    ViewData["Title"] = "CurrentVisitorsView";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<section class="hero">

    <div class="col-md-6">
        <div class="vertical-menu">
            <nav class="nav">
                <a href="@Url.Action("History", "Visitor")">
                    <span>History</span>
                </a>
                <a href="@Url.Action("CurrentVisitors", "Visitor")" class="active">
                    <span>Current Visitors</span>
                </a>
                <a href="@Url.Action("Index", "Visitor")">
                    <span>Check in visitor</span>
                </a>
                <a href="@Url.Action("Register", "Account")">
                    <span>Register new admin</span>
                </a>
                <a href="@Url.Action("LogOut", "Account")">Log Out</a>
            </nav>
        </div>
    </div>

    <div class="col-md-6">
        <h2>Visitors checked in now</h2>
        <br />

        <div style="height:700px; overflow-y:scroll;">
            @foreach (Visitor visitor in Model)
            {
                if (visitor.CheckInTime > visitor.CheckOutTime)
                {
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <p><b> Name: @visitor.FirstName @visitor.LastName</b></p>
                            <p><b> Id: @visitor.RandomNumber</b></p>
                            <p><b> Check In: @visitor.CheckInTime</b></p>
                        </div>
                        <div class="col-md-6">
                            <img src="~/visitorPhotos/@(visitor.RandomNumber).jpg" style="width: 200px" align="right" />
                        </div>
                    </div>
                    <br />
                    using (Html.BeginForm("CheckOut", "Visitor"))
                    {
                        <input type="hidden" name="RandomNumberInput" value="@visitor.RandomNumber" />
                        <input class="btn btn-xs btn-danger" style="width:auto" type="submit" value="Check out this visitor" />
                    }
                    <hr />
                }
            }
        </div>
    </div>
</section>

JonTimExamen/JonTimExamen/Views/Visitor/History.cshtml
@model List<Visitor>
@{
    ViewData["Title"] = "History";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<section class="hero">
    <div class="col-md-6">
        <div class="vertical-menu">
            <nav class="nav">
                <a href="@Url.Action("History", "Visitor")" class="active">
                    <span>History</span>
                </a>
                <a href="@Url.Action("CurrentVisitors", "Visitor")">
                    <span>Current Visitors</span>
                </a>
                <a href="@Url.Action("Index", "Visitor")">
                    <span>Check in visitor</span>
                </a>
                <a href="@Url.Action("Register", "Account")">
                    <span>Register new admin</span>
                </a>
                <a href="@Url.Action("LogOut", "Account")">Log Out</a>
            </nav>
        </div>
    </div>

    <div class="col-md-6">
        <h2>Visitor history</h2>
        <br />

        <div style="height:700px; overflow-y:scroll;">
            @foreach (Visitor visitor in Model)
            {
                if (visitor.CheckInTime < visitor.CheckOutTime)
                {
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <p><b> Name: @visitor.FirstName @visitor.LastName</b></p>
                            <p><b> Id: @visitor.RandomNumber</b></p>
                            <p><b> Check In: @visitor.CheckInTime</b></p>
                            <p><b> Check Out: @visitor.CheckOutTime</b></p>
                        </div>
                        <div class="col-md-6">
                            <img src="~/visitorPhotos/@(visitor.RandomNumber).jpg" style="width: 200px" align="right" />
                        </div>
                    </div>
                    <p style="opacity: 0">Det här är en fuling</p>
                    <hr />
                }
            }
        </div>
    </div>
</section>

JonTimExamen/JonTimExamen/Views/Visitor/Index.cshtml
@model Visitor
@{
    ViewData["Title"] = "CheckIn";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}


@if (User.Identity.IsAuthenticated)
{
    <section class="hero">
        <div class="col-md-6">
            <div class="vertical-menu">
                <nav class="nav">
                    <a href="@Url.Action("History", "Visitor")">
                        <span>History</span>
                    </a>
                    <a href="@Url.Action("CurrentVisitors", "Visitor")">
                        <span>Current Visitors</span>
                    </a>
                    <a href="@Url.Action("Index", "Visitor")" class="active">
                        <span>Check in visitor</span>
                    </a>
                    <a href="@Url.Action("Register", "Account")">
                        <span>Register new admin</span>
                    </a>
                    <a href="@Url.Action("LogOut", "Account")">Log Out</a>
                </nav>
            </div>
        </div>

        <div class="col-md-6" style="width:400px">
            <h2>Check in visitor</h2>
            <br />

            <form method="post" asp-controller="Visitor" asp-action="CheckIn">

                <div class="form-group">
                    <label asp-for="@Model.FirstName"></label>
                    <input asp-for="@Model.FirstName" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <label asp-for="@Model.LastName"></label>
                    <input asp-for="@Model.LastName" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Company"></label>
                    <input asp-for="@Model.Company" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Check In" class="btn btn-success center-block" />
                </div>
            </form>
        </div>

    </section>
}
else
{

    <section class="hero">
        <div class="row" style="margin:auto; width:400px">
            <form method="post" asp-controller="Visitor" asp-action="CheckIn">

                <div class="form-group">
                    <label asp-for="@Model.FirstName">First name</label>
                    <input asp-for="@Model.FirstName" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <label asp-for="@Model.LastName">Last name</label>
                    <input asp-for="@Model.LastName" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <label asp-for="@Model.Company">Company</label>
                    <input asp-for="@Model.Company" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Check In" class="btn btn-success center-block" />
                </div>
            </form>
        </div>
    </section>
}

JonTimExamen/JonTimExamen/Views/Visitor/QrView.cshtml
@model  List<Visitor>
@{
    ViewData["Title"] = "QrView";
}

<body>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form method="post" asp-controller="Visitor" asp-action="Print">
                <div class="form-group">
                    @if (ViewBag.visitor != null)
                    {
                        var name = ViewBag.visitor.FirstName;
                        var lastName = ViewBag.visitor.LastName;
                        var company = ViewBag.visitor.Company;
                        var number = ViewBag.visitor.RandomNumber;

                        <p><b>@name  @lastName</b></p>
                        <qrcode content="@number" width="200" height="200" />
                        <p><b>@number</b></p>
                    }
                </div>

                <div class="form-group">
                    @*<a type="button" href="javascript:window.print()">Click to Print This Page</a>*@
                    <input class="btn btn-success" type="button" value="Print" onclick="javascript: window.print();"/>
                </div>
            </form>
        </div>
    </div>
</body>

JonTimExamen/JonTimExamen/Views/Visitor/Thx.cshtml
@{
    ViewData["Title"] = "Thx";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}

<body onload="showThxText()">
    <section class="hero">
        <div class="hero-inner" id="checkoutHeroText" style="margin: auto; text-align: center">
            <h1 id="checkoutHeroH1" style="display: none">Thank you for visiting *Company</h1>
        </div>
    </section>
</body>



<script src="~/js/site.js"></script>